name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  nohup dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &> backend.log &
                  sleep 20  # Increase the wait time to allow the backend to initialize
                  tail -f backend.log  # Show logs to check for any startup issues

            - name: Check if Backend is running
              run: |
                  curl -v http://localhost:6969 || echo "Backend not accessible"
                  # Or use https if needed:
                  # curl -v https://localhost:42069

            - name: Wait for Backend to be ready
              run: |
                  # Wait for the backend to be up and ready, increase the timeout and check with the correct port
                  npx wait-on http://localhost:6969 --timeout 300000 --interval 5000
                  # Or use https if needed:
                  # npx wait-on https://localhost:42069 --timeout 300000 --interval 5000

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Wait for Frontend to be ready
              run: |
                  # Wait for the frontend to be up
                  npx wait-on http://localhost:3000 --timeout 300000 --interval 5000

            - name: Run Cypress tests
              run: pnpm npx cypress run
