name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  # Start the backend (if running as a .NET app)
                  dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &

            - name: Wait for Backend to be ready
              run: |
                  # Wait for the backend to be up and ready (adjust port if needed)
                  npx wait-on http://localhost:6969 --timeout 120000 --interval 5000  # Adjust timeout and port if necessary

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Wait for Frontend to be ready
              run: |
                  # Wait for the frontend to be up (adjust port if needed)
                  npx wait-on http://localhost:3000 --timeout 60000 --interval 5000  # Adjust timeout and port if necessary

            - name: Run Cypress tests
              run: pnpm npx cypress run
