name: End-to-end tests

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              working-directory: ./cypress
              run: npm install -g pnpm

            - name: Install dependencies
              working-directory: ./cypress
              run: pnpm install -r

            - name: Run docker-compose
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                  compose-file: './docker-compose.yml'

            - name: Wait for DB to be ready
              run: |
                  # Wait for the database to be ready using a SQL check
                  until /opt/mssql-tools/bin/sqlcmd -S database -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" &>/dev/null; do
                      echo "Waiting for database..."
                      sleep 5  # Wait 5 seconds before retrying
                  done
                  echo "Database is ready!"

            - name: Run Cypress tests
              working-directory: ./cypress
              run: pnpm npx cypress run
