name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: pnpm install

            - name: Start server and wait
              run: |
                  pnpm start &
                  pnpm npx wait-on http://localhost:3000

            - name: Run Cypress tests
              run: pnpm npx cypress run
