name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install frontend dependencies
              working-directory: ./react-app
              run: pnpm install

            - name: Build backend project
              working-directory: ./Backend-Example
              run: dotnet build ./Presentation/Presentation.csproj

            - name: Start backend server
              working-directory: ./Backend-Example
              run: |
                  dotnet run --project ./Presentation/Presentation.csproj &
                  npx wait-on http://localhost:42069

            - name: Start frontend server
              working-directory: ./react-app
              run: |
                  pnpm start &
                  npx wait-on http://localhost:3000

            - name: Run Cypress tests
              working-directory: ./react-app
              run: pnpm npx cypress run
