name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  # Start the backend in the background
                  nohup dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &> backend.log &
                  # Wait for the backend to be fully initialized by checking if the Swagger UI is accessible
                  timeout=300
                  end=$((SECONDS+timeout))
                  while [ $SECONDS -lt $end ]; do
                    # Check if the Swagger UI is accessible
                    curl --insecure https://localhost:42069/swagger/index.html && break
                    echo "Waiting for backend to be ready..."
                    sleep 5
                  done
                  if [ $SECONDS -ge $end ]; then
                    echo "Backend did not start in time."
                    exit 1
                  fi

            - name: Start Frontend Server
              run: |
                  # List files in the current directory for debugging
                  echo "Listing current directory contents"
                  ls -la

                  # Change to the frontend directory
                  cd ./react-app
                  echo "Changed directory to $(pwd)"

                  # Ensure pnpm is available in the frontend directory
                  pnpm --version

                  # Start the frontend and run in the background
                  nohup pnpm start &> frontend.log &

                  # Wait for the frontend to be fully initialized by checking if it's accessible
                  timeout=300
                  end=$((SECONDS+timeout))
                  while [ $SECONDS -lt $end ]; do
                    # Check if the frontend is available at http://localhost:3000
                    curl --insecure http://localhost:3000 && break
                    echo "Waiting for frontend to be ready..."
                    sleep 5
                  done
                  if [ $SECONDS -ge $end ]; then
                    echo "Frontend did not start in time."
                    exit 1
                  fi

            - name: Run Cypress tests
              run: pnpm npx cypress run
