name: End-to-End Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  cd ./Backend-Example
                  dotnet build --project ./Presentation/Presentation.csproj
                  nohup dotnet run --project ./Presentation/Presentation.csproj > backend.log 2>&1 &

            - name: Wait for Backend to be ready
              run: |
                  timeout=600  # Timeout set to 10 minutes
                  end=$((SECONDS+timeout))
                  while [ $SECONDS -lt $end ]; do
                    curl --insecure http://localhost:6969 && break
                    echo "Waiting for backend to be ready..."
                    sleep 5
                  done
                  if [ $SECONDS -ge $end ]; then
                    echo "Backend did not start in time."
                    cat backend.log
                    exit 1
                  fi

            - name: Start Frontend Server
              run: |
                  # Navigate to the frontend directory
                  cd ./react-app
                  echo "Changed directory to $(pwd)"

                  # Install dependencies (if necessary) and start the frontend
                  pnpm install
                  nohup pnpm start > frontend.log 2>&1 &

                  # Wait for the frontend to be ready
                  timeout=600  # Timeout set to 10 minutes
                  end=$((SECONDS+timeout))
                  while [ $SECONDS -lt $end ]; do
                    curl --insecure http://localhost:3000 && break
                    echo "Waiting for frontend to be ready..."
                    sleep 5
                  done
                  if [ $SECONDS -ge $end ]; then
                    echo "Frontend did not start in time."
                    cat frontend.log  # Show frontend logs for debugging
                    exit 1
                  fi

            - name: Run Cypress tests
              run: |
                  # Cypress tests are executed once both the backend and frontend are ready
                  npx cypress run
