name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  nohup dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &> backend.log &
                  sleep 20  # Increase the wait time to allow the backend to initialize
                  tail -f backend.log  # Show logs to check for any startup issues

            - name: Check if Backend is accessible
              run: |
                  # Use curl to verify if Swagger UI is accessible
                  curl --insecure https://localhost:42069/swagger/index.html || echo "Backend is not accessible"

            - name: Wait for Backend to be ready
              run: |
                  # Wait for the Swagger UI to be up and accessible on the correct port
                  npx wait-on --timeout 300000 --interval 5000 https://localhost:42069/swagger/index.html

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Wait for Frontend to be ready
              run: |
                  # Wait for the frontend server to be up and running on port 3000
                  npx wait-on http://localhost:3000 --timeout 300000 --interval 5000

            - name: Run Cypress tests
              run: pnpm npx cypress run
