name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  nohup dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &> backend.log &
                  sleep 10  # Give it some time to initialize before moving on
                  tail -f backend.log  # Log output for debugging

            - name: Wait for Backend to be ready
              run: |
                  # Wait for the backend to be up and ready (adjust timeout if needed)
                  npx wait-on https://localhost:42069 --timeout 180000 --interval 5000

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Wait for Frontend to be ready
              run: |
                  # Wait for the frontend to be up (adjust port if needed)
                  npx wait-on http://localhost:3000 --timeout 60000 --interval 5000

            - name: Run Cypress tests
              run: pnpm npx cypress run
