name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  # Start the backend (if running as a .NET app)
                  dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &

            - name: Wait for Backend to be ready
              run: |
                  npx wait-on http://localhost:6969 --timeout 60000 --interval 5000  # Make sure the correct port is here

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Run Cypress tests
              run: |
                  pnpm npx cypress run
