name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Start Backend Server
              run: |
                  # Start the backend in the background
                  nohup dotnet run --project ./Backend-Example/Presentation/Presentation.csproj &> backend.log &
                  # Wait for the backend to be fully initialized by checking if the Swagger UI is accessible
                  timeout=300
                  end=$((SECONDS+timeout))
                  while [ $SECONDS -lt $end ]; do
                    # Check if the Swagger UI is accessible
                    curl --insecure https://localhost:42069/swagger/index.html && break
                    echo "Waiting for backend to be ready..."
                    sleep 5
                  done
                  if [ $SECONDS -ge $end ]; then
                    echo "Backend did not start in time."
                    exit 1
                  fi

            - name: Start Frontend Server
              run: |
                  cd ./react-app
                  pnpm start &

            - name: Wait for Frontend to be ready
              run: |
                  # Wait for the frontend to be up and running on port 3000
                  npx wait-on http://localhost:3000 --timeout 300000 --interval 5000

            - name: Run Cypress tests
              run: pnpm npx cypress run
